In [1]:
import numpy as np
from data_prep import features, targets, features_test, targets_test

np.random.seed(21)

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x) :
    return sigmoid ( x ) * ( 1 - sigmoid(x))

# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

In [39]:
for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        
        hidden_input = np.dot(x , weights_input_hidden )
        hidden_output = sigmoid(hidden_input)
        output = sigmoid (np.dot ( hidden_output , weights_hidden_output  ))
        ##############
        ## Backward pass ##
        # TODO: Calculate the network's prediction error
        error = y - output
        error
        # TODO: Calculate error term for the output unit
        output_error_term = error * sigmoid_prime(output)

        ## propagate errors to hidden layer
        
        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(output_error_term , weights_hidden_output )

        # TODO: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * sigmoid_prime (hidden_output)

        # TODO: Update the change in weights
        del_w_hidden_output += output_error_term * hidden_output
        del_w_input_hidden += hidden_error_term * x[:,None]

    # TODO: Update weights  (don't forget to division by n_records or number of samples)
    weights_input_hidden += del_w_input_hidden * learnrate / n_records
    weights_hidden_output +=  del_w_hidden_output* learnrate / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

Train loss:  0.2400019238649666
Train loss:  0.23905473044572362
Train loss:  0.23813837219584547
Train loss:  0.23725194416303488
Train loss:  0.23639456612154752
Train loss:  0.23556538208032735
Train loss:  0.23476355978299365
Train loss:  0.2339882902018073
Train loss:  0.2332387870275585
Train loss:  0.23251428615710149
Prediction accuracy: 0.700


In [3]:
del_w_hidden_output

array([-2.34585145,  2.38315546])

In [4]:
weights_hidden_output

array([ 0.65768472, -0.28137626])

In [5]:
hidden_error_term

array([0.02643598, 0.01131225])

In [6]:
h

array([-0.7608793 ,  0.81148034])

In [7]:
x

array([-1.27860482, -1.6551629 ,  0.        ,  1.        ,  0.        ,
        0.        ])

In [9]:
weights_input_hidden

array([[-0.0212469 , -0.0453625 ],
       [ 0.42527918, -0.51302857],
       [ 0.30427067, -0.69850167],
       [-0.08407636, -0.09573023],
       [ 0.4605303 , -0.00512142],
       [-0.25037055,  0.56083908]])

In [11]:
sigmoid(np.dot(x, weights_input_hidden))


array([0.31846907, 0.69241123])

In [12]:
out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))

In [13]:
out

0.5036559729127831

In [16]:
del_w_input_hidden = np.zeros(weights_input_hidden.shape)

In [17]:
del_w_input_hidden

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros(weights_hidden_output.shape)


array([0., 0.])

In [23]:
output - hidden_input

array([ 1.26240396, -0.30910925])

In [24]:
weights_hidden_output

array([ 0.65768472, -0.28137626])

In [25]:
np.dot(output_error_term, weights_hidden_output)

array([-0.07778173,  0.03327724])

In [26]:
output_error_term

-0.1182659787951287

In [27]:
weights_hidden_output

array([ 0.65768472, -0.28137626])

In [30]:
x[:, None]

array([[-1.27860482],
       [-1.6551629 ],
       [ 0.        ],
       [ 1.        ],
       [ 0.        ],
       [ 0.        ]])

In [31]:
x

array([-1.27860482, -1.6551629 ,  0.        ,  1.        ,  0.        ,
        0.        ])

In [32]:
x.transpose

<function ndarray.transpose>

In [33]:
np.transpose(x)

array([-1.27860482, -1.6551629 ,  0.        ,  1.        ,  0.        ,
        0.        ])

In [35]:
x.T

array([-1.27860482, -1.6551629 ,  0.        ,  1.        ,  0.        ,
        0.        ])

In [40]:
import numpy as np
from data_prep import features, targets, features_test, targets_test

np.random.seed(21)

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        hidden_input = np.dot(x, weights_input_hidden)
        hidden_output = sigmoid(hidden_input)

        output = sigmoid(np.dot(hidden_output,
                                weights_hidden_output))

        ## Backward pass ##
        # TODO: Calculate the network's prediction error
        error = y - output

        # TODO: Calculate error term for the output unit
        output_error_term = error * output * (1 - output)

        ## propagate errors to hidden layer

        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(output_error_term, weights_hidden_output)

        # TODO: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)

        # TODO: Update the change in weights
        del_w_hidden_output += output_error_term * hidden_output
        del_w_input_hidden += hidden_error_term * x[:, None]

    # TODO: Update weights
    weights_input_hidden += learnrate * del_w_input_hidden / n_records
    weights_hidden_output += learnrate * del_w_hidden_output / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))


Train loss:  0.25135725242598617
Train loss:  0.24996540718842886
Train loss:  0.24862005218904654
Train loss:  0.24731993217179746
Train loss:  0.24606380465584848
Train loss:  0.24485044179257162
Train loss:  0.2436786320186832
Train loss:  0.24254718151769536
Train loss:  0.24145491550165465
Train loss:  0.24040067932493367
Prediction accuracy: 0.725
